### ISSUE TITLE
Documentação traduzida

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodebr#19]
Traduzir a documentação oficial para pt-BR

**Comment by alanhoff** [comment]
Quem vai ajudar? http://www.meetup.com/NodeBR-Sao-Paulo/events/220194999/

**Comment by marcosbergamo** [comment]
Na quarta feira, no evento no caso vamos distribuir os grupos para a
tradução. Dai iremos reservar uma rota no site para renderizar algo como o
próprio site do nome.js

**Comment by alanhoff** [comment]
Fechando esta issue no momento. No futuro devemos voltar para analisar.
