### ISSUE TITLE
Gitter.im

### ISSUE THREAD

**Issue by jefperito** [nodebr/nodebr#55]
Pessoal, ando colaborando em outros projetos open source e o pessoal ta começando a utilizar esse chat integrado ao github:
https://gitter.im/

Achei muito top esse chat e o que acham dele aqui?

O projeto que ando colaborando colocaram o badget do chat no Readme.md:

https://github.com/chigby/mtg

**Comment by alanhoff** [comment]
Acho que seria baca, aceitamos uma pull com a badget :-)


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 15 de maio de 2015 11:13, Jeferson <notifications@github.com> escreveu:

**Comment by thebergamo** [comment]
+1 @jefperito

**Comment by alanhoff** [comment]
Fechando esta issue no momento. Já temos o [Slack](https://slack.nodebr.org).
