### ISSUE TITLE
Criação de página com links úteis

### ISSUE THREAD

**Issue by afucher** [nodebr/nodebr#56]
Criar uma página, e pode ser aqui mesmo no github como um .io ou wiki mesmo, onde colocaríamos links de tutoriais/textos sobre Node.js e também sobre os módulos.

Pensei em uma estrutura assim:
- Node.js
  - arquivo_com_links
  - Módulos
    - Express
      - arquivo_com_links
    - Hapi
      - arquivo_com_links

E o arquivo em si de links, ainda tenho dúvidas do melhor:
##### Tutoriais
- [Tutorial 1](link.com.br) - Assunto do tutorial  
##### Textos
- [Texto 1](link.com.br) - Assunto do texto  
##### Autenticação
- [Tutorial 1](link.com.br) - Autenticação utilizando texugos  
- [Texto 1](link.com.br) - Autenticação por código morse

**Comment by thebergamo** [comment]
Acho que isso pode ser o primeiro passo da nossa Weekly também =D

**Comment by alanhoff** [comment]
Fechando esta issue no momento. No futuro devemos voltar para analisar.
