### ISSUE TITLE
O grande compilado de ideias aleatorias

### ISSUE THREAD

**Issue by cezaraugusto** [nodebr/nodebr#57]
Pessoal, nossa comunidade é vibrante mas está dispersa. A seara é realmente grande, mas poucos os ceifeiros.

Eu li as issues antigas aqui, algumas tem ideias que pensei, mas parece que a maioria não teve tração. Bom, todo mundo tem seu trabalho e suas atividades, mas acho que se a gente se organizar em tarefas pequenas ou grupos, a gente consegue processar melhor.

Desculpem se parecer pretensioso, meu único objetivo é devolver à comunidade. Trabalho voluntário precisa ser aplaudido, não criticado. Seguem minhas ideias para melhorar nossa comunidade:
# O grande compilado de ideias aleatórias
## Melhorar (transformar?) o site oficial (nodebr.com).

Acho que a comunidade tem de tudo pra crescer e pegar a galera que veio do front-end e quer mergulhar em Node porque, afinal, é JavaScript. O problema é que o site não é amigável (o site é feio mesmo), não mostra o "pra quê" nem o "por quê" e é feito em Jekill. Pode parecer babaquice, mas eu não confiaria em um vendedor que jura que o Trakinas é seu biscoito favorito, mas se apresenta comendo Negresco. Poderia ser em Harp ou Hexo, desde que fosse feito em... Node!
## Reunir os membros mais vibrantes da comunidade, aqui

Essa organização aqui, do GitHub, deveria ter como membros o pessoal vibrante. Dá credibilidade. Caras como o Rodrigo Branas, o Filipe Deschamps, dentre outros, ao se juntar à comunidade trazem em conjunto as pessoas que admiram o trabalho deles. A comunidade fica coesca e endossa o padrão de qualidade. Além de servir de canal de divulgação para ambos os lados.
## Criação de uma seção com tutoriais (#3)

Eu entendo (eu entendo de verdade) que criar conteúdo leva tempo e dedicação. Enquanto não houverem conteúdos daqui a serem expostos, porque não fazer um compilado dos artigos mais educativos (mesmo que externos) e disponibilizar os links? Quase um roadmap, onde o usuário siga o NodeBr como referência para o ensino e divulgação da comunidade.
## Difundir a comunidade para os desenvolvedores em potencial

Eu estou a produzir um artigo sobre o porquê o Node é incrível. Um dos pontos é que o Node possibilitou a mim (e a tantos outros) desenvolvedores front-end, a seguir o caminho do Node. Me fez confortável a trabalhar "do outro lado" e existem inúmeros desenvolvedores que sonham em sair das garras de outras linguagens. A comunidade aqui precisa ser o marco zero, o _go to_ se tratando de Node no Brasil.
## Bot do Twitter (#34)

A ideia do bot do Twitter é bem legal, isso chegou a ser produzido?
## Styleguide (#29)

Fazer um styleguide semelhante ao [Node Style Guide](https://github.com/felixge/node-style-guide) (fecharia o #29). Clonar o repo e disponibilizar aqui para adaptar aos padrões daqui. Alguém nativo do grupo poderia definir os padrões e deixar aberto para quem quiser contribuir.
## Contribution Guidelines (também #29)

Primeiro teria que definir quais projetos seriam abertos à comunidade e basear num modelo (eu fiz um [aqui](https://github.com/cezaraugusto/github-template-guidelines/blob/master/.github/CONTRIBUTING.md)). Mas para ter uma guideline os projetos deveriam ser abertos de forma mais clara (algum ponto no readme do repo principal, por exemplo, listando as issues)
## Tradução da Documentação (#19)

Traduzir documentação técnica requer um esforço heróico. O Christopher EnyTC (@chrisenytc) chegou a iniciar um trabalho, mas foi interrompido (e pela data ficou desatualizado). Chegamos à versão 6, acho que é uma boa hora para fazer um esforço coletivo nisso.

Eu estou empenhado em traduzir o [YDKJS](https://github.com/cezaraugusto/You-Dont-Know-JS), que além de grande tem tópicos que carecem de tradução, mas o resultado está sendo incrível então acho que vale muito apena focar nessa parte, especificamente. Seguiria a linha do "a comunidade NodeBr é o go-to da parada se tratando de Node no Brasil".
## Relacionar desenvolvedores e empregadores (#1 e #12)

Unir o pessoal. Como eu falei em um outro tópico dessa lista gigante: O NodeBr precisa ser o canal principal sobre Node no Brasil. Quer aprender? NodeBr. Quer contratar? NodeBr. Quer fazer novos amigos? NodeBr. Meio que uma religião. Aliás, é esse o termo mesmo. Acho que o grupo precisa realmente _evangelizar_ sobre a comunidade.

É isso.

Novamente amigos, de forma alguma quis ser pretensioso. A comunidade é inspiradora e me senti motivado a escrever tudo isso. Adoraria saber a opinião dos outros colegas.

**Comment by albertosouza** [comment]
Sobre o nodebr.com acho que poderia ter os links das ferramentas da comunidade como o github, skack ... etc e na parte de posts virar um agredador de feeds de outros sites mantendo a referencia dos criadores dos conteúdos.

**Comment by alanhoff** [comment]
o nodebr.com não é nosso, ele pertence ao @rafadev7, o qual já disse que não tem interesse em ceder o domínio no momento, por isso precisamos usar o nodebr.org

**Comment by cezaraugusto** [comment]
@alanhoff acho então que é o caso dar um ping no pessoal do NodeJs.org porquê o link para a comunidade no Brasil é o nodebr.com. A ambiguidade confunde a todos. 

Fonte aqui: https://nodejs.org/en/get-involved/

**Comment by alanhoff** [comment]
@cezaraugusto totalmente de acordo, mas primeiro precisamos ter algo no ar :P

**Comment by rodrigobaron** [comment]
Sobre a ref #1, acho interessante em fazer algo parecido com o [RubyJobs](http://www.rubyjobs.me), apenas um *middleware entre empresa e dev :smile: .

**Comment by albertosouza** [comment]
O http://nodebr.org é mais legal para o projeto.

**Comment by cezaraugusto** [comment]
@alanhoff acredito que o conteúdo ainda seja pouco, mas poderia dizer os itens básicos como:

* Quem somos
* O que fazemos
* Objetivos
* Notícias (ok, não tem nenhuma mas uma "o nodebr está no ar!" já é um começo
* Precisamos de você! (e um link para as milestones aqui no repo sobre o que precisamos fazer)

Acho que o ponto forte seria dizer a missão da comunidade, e como os early adopters podem contribuir para crescer. A comunidade vibra, mas precisa de um farol!

**Comment by rafadev7** [comment]
@alanhoff não lembro de ter falado isso.
Sou totalmente a favor de tudo que possa ser feito para favorecer a comunidade.
O domínio está disponível, porém precisa de um projeto conciso  com objetivos claros e aprovado pela maioria da comunidade.

**Comment by goenning** [comment]
Não deixem a thread morrer! O Alan reativou o podcast recentemente e, assim como ele, vamos tirar do papel e começar a botar as ideias em prática. 

Fiz um setup inicial de uma proposta de site para o nodebr.org para ver se o pessoal se anima em contribuir.

Repositório: https://github.com/goenning/nodebr.org
Live: http://goenning.net/nodebr.org/

Está fazendo deploy via travis, então se alguém quiser colaborar é só fazer commitar na master e o site é atualizado.

Se aceito, podemos migrar para esta organização.

**Comment by alanhoff** [comment]
Fechando esta issue no momento. No futuro devemos voltar para analisar.
