### ISSUE TITLE
Estrutura base do projeto

### ISSUE THREAD

**Issue by thebergamo** [nodebr/nodebr#59]
Essa issue é referente a montar uma estrutura base do projeto. Sinta-se a vontade para escolher a stack que mais lhe agrada ao fazer isso.
Apenas algumas pequenas observações devem ser validadas:
- Os dados da API são relacionais, então nada de NoSQL. (Preferencialmente PostgreSQL)

**Comment by dalssoft** [comment]
Sprinklr's NodeJS boilerplate - https://github.com/scup/nodebase (sem dependências)

**Comment by alanhoff** [comment]
Esqueci de botar no commit, mas a base está pronta já.
