### ISSUE TITLE
Endpoint de Usuário

### ISSUE THREAD

**Issue by thebergamo** [nodebr/nodebr#60]
Devemos criar um endpoint para contemplar a criação de usuários

Para mais informações sobre esse endpoint, acesso o [Apiary](http://docs.nodebr.apiary.io/#reference/0/usuario/cria-um-usuario)

**Comment by thebergamo** [comment]
@alanhoff vamos tratar de enviar emails nesse momento?

**Comment by alanhoff** [comment]
@thebergamo não, sem e-mails na primeira versão

**Comment by thebergamo** [comment]
@brunops como não está na org não consegui assinar pra vc essa issue.

**Comment by thebergamo** [comment]
removi a necessidade de criar o recurso de sessão, pois ele pode ser uma tarefa separada.

**Comment by thebergamo** [comment]
fechado com o PR #64
