### ISSUE TITLE
Qual é a lista de páginas para o Front-End e especificação básica?

### ISSUE THREAD

**Issue by yamadapc** [nodebr/nodebr#62]
Esse patch conserta a compilação e execução do `frontend`: https://gist.github.com/48179a2236191858b2fa171d04fe86fc

- - -

Queria entender melhor quais são as páginas sendo desenvolvidas e seus propósitos.

A partir do menu parece que:

- News
  * CRUD - Lista, detalhe, criar, editar, comentários
  * [ ] Lista
     - [x] Cards de notícia e view de lista
     - [ ] Integrar lista com uma API
     - [ ] Paginação
  * [ ] Detalhe
  * [ ] Criar
- Eventos
  * CRUD - Lista, detalhe, criar, editar
  * [ ] Lista
  * [ ] Detalhe
  * [ ] Criar
- Vagas
  * CRUD - Lista, detalhe, criar, editar
  * [ ] Lista
  * [ ] Detalhe
  * [ ] Criar
- Comunidade
- Login
- **Podcasts** ( ping @thebergamo )
  * [ ] Lista
  * [ ] Detalhe

Ping @alanhoff 

- - -

[2¢] Talvez fosse mais pragmático fazer um site estático e usar o GitHub pra as pessoas contribuírem com conteúdo.

**Comment by thebergamo** [comment]
@alanhoff acho que seria legal ter um roadmap mais explicito das features mesmo.

**Comment by alanhoff** [comment]
@yamadapc a base do projeto ainda não está pronto, mas no momento seria apenas login, cadastro, lista e envio de compartilhamentos. Assim que isso estiver pronto vou avisar o pessoal, aí teremos um esqueleto sólido para o frontend :-)
